const colors = {
  light: {
    text: "#0B0B1E",
    tint: "#5B4EFF",
    background: "#F6F7FF",
    foreground: "#0B0B1E",
    card: "#FFFFFF",
    cardForeground: "#0B0B1E",
    primary: "#5B4EFF",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F1F8",
    secondaryForeground: "#0B0B1E",
    muted: "#F0F1F8",
    mutedForeground: "#7B7D9D",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E8EAF6",
    input: "#E8EAF6",
    success: "#10B981",
    warning: "#F59E0B",
    gold: "#FFB800",
  },
  dark: {
    text: "#F0F1FF",
    tint: "#7B72FF",
    background: "#0B0B1E",
    foreground: "#F0F1FF",
    card: "#14142B",
    cardForeground: "#F0F1FF",
    primary: "#7B72FF",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E3A",
    secondaryForeground: "#F0F1FF",
    muted: "#1E1E3A",
    mutedForeground: "#8B8FA8",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E3A",
    input: "#1E1E3A",
    success: "#10B981",
    warning: "#F59E0B",
    gold: "#FFB800",
  },
  radius: 12,
};

export default colors;
