<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Vendor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = Vendor::pluck('id', 'shop_name');

        $products = [
            [
                'title' => 'Nike Air Max 270',
                'description' => 'Original Nike Air Max 270. Lightweight, breathable upper with Max Air cushioning for all-day comfort. Available in multiple sizes.',
                'price' => 85000,
                'original_price' => 105000,
                'stock' => 24,
                'sold_count' => 3400,
                'category' => 'Shoes',
                'vendor' => 'Kicks Hub NG',
                'images' => ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'],
                'tags' => ['nike', 'sneakers', 'running'],
                'is_dropshipping' => false,
                'ai_optimized' => true,
                'free_shipping' => true,
                'rating' => 4.8,
                'review_count' => 128,
                'variants' => [['label' => 'Size', 'options' => ['39', '40', '41', '42', '43', '44', '45']]],
            ],
            [
                'title' => 'iPhone 15 Pro Max 256GB',
                'description' => 'Apple iPhone 15 Pro Max, 256GB, Titanium finish. A17 Pro chip, 48MP camera system, USB-C charging. Sealed in box with full warranty.',
                'price' => 950000,
                'original_price' => 1100000,
                'stock' => 8,
                'sold_count' => 1800,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400'],
                'tags' => ['apple', 'iphone', 'smartphone'],
                'is_dropshipping' => false,
                'ai_optimized' => true,
                'free_shipping' => true,
                'rating' => 4.9,
                'review_count' => 312,
                'variants' => [['label' => 'Color', 'options' => ['Natural Titanium', 'Black Titanium', 'Blue Titanium']]],
            ],
            [
                'title' => 'Adidas Floral Summer Dress',
                'description' => 'Lightweight floral sundress perfect for the Lagos heat. Breathable cotton blend, adjustable straps, flattering A-line silhouette.',
                'price' => 18500,
                'original_price' => 25000,
                'stock' => 45,
                'sold_count' => 920,
                'category' => 'Fashion',
                'vendor' => 'Adaeze Fashion Hub',
                'images' => ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400'],
                'tags' => ['dress', 'fashion', 'summer'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.5,
                'review_count' => 67,
                'variants' => [
                    ['label' => 'Size', 'options' => ['XS', 'S', 'M', 'L', 'XL']],
                    ['label' => 'Color', 'options' => ['Blue Floral', 'Pink Floral', 'Yellow Floral']],
                ],
            ],
            [
                'title' => 'Samsung 55" 4K Smart TV',
                'description' => 'Samsung 55-inch Crystal UHD 4K Smart TV. Alexa built-in, 3 HDMI ports, WiFi 5GHz. Crystal Processor 4K for brilliant picture quality.',
                'price' => 320000,
                'original_price' => 380000,
                'stock' => 12,
                'sold_count' => 560,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400'],
                'tags' => ['samsung', 'tv', '4k'],
                'is_dropshipping' => true,
                'ai_optimized' => true,
                'free_shipping' => false,
                'rating' => 4.7,
                'review_count' => 89,
                'variants' => [],
            ],
            [
                'title' => 'Luxury Face Serum Set',
                'description' => 'Premium anti-aging face serum set with Vitamin C, Retinol, and Hyaluronic Acid. 3-piece set for complete skincare routine.',
                'price' => 12500,
                'original_price' => 18000,
                'stock' => 60,
                'sold_count' => 5100,
                'category' => 'Beauty',
                'vendor' => 'GlowUp Beauty',
                'images' => ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400'],
                'tags' => ['skincare', 'beauty', 'serum'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.6,
                'review_count' => 203,
                'variants' => [],
            ],
            [
                'title' => 'Jordan 1 Retro High OG',
                'description' => 'Air Jordan 1 Retro High OG. Authentic Nike product. Leather upper, Air-Sole unit, rubber outsole. Classic colorway.',
                'price' => 120000,
                'original_price' => 145000,
                'stock' => 5,
                'sold_count' => 2800,
                'category' => 'Shoes',
                'vendor' => 'Kicks Hub NG',
                'images' => ['https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400'],
                'tags' => ['jordan', 'nike', 'sneakers'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.9,
                'review_count' => 445,
                'variants' => [['label' => 'Size', 'options' => ['40', '41', '42', '43', '44', '45']]],
            ],
            [
                'title' => 'Stainless Steel Water Bottle 1L',
                'description' => 'Double-walled vacuum insulated stainless steel water bottle. Keeps drinks cold 24hrs, hot 12hrs. BPA-free, leak-proof lid.',
                'price' => 5800,
                'original_price' => null,
                'stock' => 150,
                'sold_count' => 12500,
                'category' => 'Home',
                'vendor' => 'HomeGoods NG',
                'images' => ['https://images.unsplash.com/photo-1581553680321-4fffae59fccd?w=400'],
                'tags' => ['bottle', 'water', 'fitness'],
                'is_dropshipping' => true,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.4,
                'review_count' => 178,
                'variants' => [['label' => 'Color', 'options' => ['Silver', 'Black', 'Rose Gold', 'Navy']]],
            ],
            [
                'title' => 'Portable Bluetooth Speaker',
                'description' => '360° surround sound, 20hr battery life, waterproof IPX7. Built-in microphone, USB-C charging, multicolor LED lighting.',
                'price' => 28000,
                'original_price' => 35000,
                'stock' => 33,
                'sold_count' => 4200,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1560393464-5c69a73c5770?w=400'],
                'tags' => ['speaker', 'bluetooth', 'music'],
                'is_dropshipping' => false,
                'ai_optimized' => true,
                'free_shipping' => true,
                'rating' => 4.6,
                'review_count' => 134,
                'variants' => [['label' => 'Color', 'options' => ['Black', 'Red', 'Blue']]],
            ],
            [
                'title' => 'Men\'s Classic Agbada Set',
                'description' => 'Premium hand-embroidered Nigerian Agbada set. 3-piece: buba, sokoto, and flowing top. Made with high-quality ASO-OKE fabric.',
                'price' => 45000,
                'original_price' => 65000,
                'stock' => 20,
                'sold_count' => 440,
                'category' => 'Fashion',
                'vendor' => 'Adaeze Fashion Hub',
                'images' => ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400'],
                'tags' => ['agbada', 'fashion', 'traditional'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.7,
                'review_count' => 56,
                'variants' => [
                    ['label' => 'Size', 'options' => ['M', 'L', 'XL', 'XXL']],
                    ['label' => 'Color', 'options' => ['Royal Blue', 'Wine', 'White', 'Gold']],
                ],
            ],
            [
                'title' => 'Smart Watch Series 8',
                'description' => 'Full health monitoring: heart rate, SpO2, sleep tracking. GPS, NFC payments, 18hr battery. Aluminum case, 100+ workout modes.',
                'price' => 75000,
                'original_price' => 95000,
                'stock' => 15,
                'sold_count' => 6700,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400'],
                'tags' => ['smartwatch', 'fitness', 'wearable'],
                'is_dropshipping' => true,
                'ai_optimized' => true,
                'free_shipping' => false,
                'rating' => 4.5,
                'review_count' => 221,
                'variants' => [['label' => 'Color', 'options' => ['Midnight', 'Starlight', 'Red', 'Blue']]],
            ],
            [
                'title' => 'Ankara Print Handbag',
                'description' => 'Handcrafted genuine leather handbag with vibrant Ankara fabric lining. Large main compartment, 2 interior pockets, adjustable strap.',
                'price' => 14000,
                'original_price' => 20000,
                'stock' => 35,
                'sold_count' => 1900,
                'category' => 'Fashion',
                'vendor' => 'Adaeze Fashion Hub',
                'images' => ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400'],
                'tags' => ['handbag', 'ankara', 'fashion'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.3,
                'review_count' => 88,
                'variants' => [['label' => 'Pattern', 'options' => ['Blue Geometric', 'Red Kente', 'Green Wax']]],
            ],
            [
                'title' => 'Protein Powder 2kg (Chocolate)',
                'description' => 'Premium whey protein isolate, 25g protein per serving. No fillers, 0g sugar. Lab-tested. 67 servings per bag. Made for serious athletes.',
                'price' => 32000,
                'original_price' => null,
                'stock' => 80,
                'sold_count' => 8900,
                'category' => 'Sports',
                'vendor' => 'FitLife Store',
                'images' => ['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=400'],
                'tags' => ['protein', 'fitness', 'sports'],
                'is_dropshipping' => true,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.6,
                'review_count' => 309,
                'variants' => [['label' => 'Flavor', 'options' => ['Chocolate', 'Vanilla', 'Strawberry']]],
            ],
            [
                'title' => 'Wireless Noise-Cancelling Headphones',
                'description' => 'Premium ANC headphones with 40hr battery. Comfort-fit ear cups, foldable design. Crystal clear audio with deep bass.',
                'price' => 45000,
                'original_price' => 65000,
                'stock' => 30,
                'sold_count' => 2300,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400'],
                'tags' => ['headphones', 'audio', 'wireless'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.7,
                'review_count' => 156,
                'variants' => [['label' => 'Color', 'options' => ['Black', 'White', 'Navy']]],
            ],
            [
                'title' => 'Yoga Mat Premium Non-Slip 6mm',
                'description' => 'Eco-friendly TPE yoga mat. Double-sided non-slip, includes carry strap. Extra thick 6mm for joint protection.',
                'price' => 8500,
                'original_price' => 12000,
                'stock' => 200,
                'sold_count' => 15200,
                'category' => 'Sports',
                'vendor' => 'FitLife Store',
                'images' => ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400'],
                'tags' => ['yoga', 'fitness', 'exercise'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.5,
                'review_count' => 420,
                'variants' => [['label' => 'Color', 'options' => ['Purple', 'Teal', 'Black', 'Pink']]],
            ],
            [
                'title' => 'African Print Maxi Skirt',
                'description' => 'Beautiful Ankara print maxi skirt. Elastic waist, flowy fit. Perfect for any occasion from casual to formal events.',
                'price' => 15500,
                'original_price' => 22000,
                'stock' => 40,
                'sold_count' => 810,
                'category' => 'Fashion',
                'vendor' => 'Adaeze Fashion Hub',
                'images' => ['https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?w=400'],
                'tags' => ['ankara', 'fashion', 'skirt'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.4,
                'review_count' => 73,
                'variants' => [
                    ['label' => 'Size', 'options' => ['S', 'M', 'L', 'XL']],
                    ['label' => 'Pattern', 'options' => ['Green Diamond', 'Blue Wave', 'Red Star']],
                ],
            ],
            [
                'title' => 'Mechanical Gaming Keyboard RGB',
                'description' => 'Hot-swappable switches, per-key RGB, PBT keycaps, USB-C detachable cable. Premium mechanical gaming keyboard.',
                'price' => 35000,
                'original_price' => 45000,
                'stock' => 55,
                'sold_count' => 4900,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400'],
                'tags' => ['gaming', 'keyboard', 'mechanical'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.8,
                'review_count' => 267,
                'variants' => [['label' => 'Switch', 'options' => ['Red', 'Blue', 'Brown']]],
            ],
            [
                'title' => 'Natural Shea Butter 500g',
                'description' => '100% organic unrefined shea butter. Moisturizing, anti-inflammatory, suitable for all skin types. Pure Nigerian shea butter.',
                'price' => 4500,
                'original_price' => null,
                'stock' => 500,
                'sold_count' => 28000,
                'category' => 'Beauty',
                'vendor' => 'GlowUp Beauty',
                'images' => ['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=400'],
                'tags' => ['skincare', 'shea butter', 'natural'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.3,
                'review_count' => 890,
                'variants' => [],
            ],
            [
                'title' => 'Adjustable Dumbbell Set 20kg',
                'description' => 'Space-saving adjustable dumbbell set. 2-in-1 design, 2kg to 20kg per pair. Replace multiple dumbbells with one set.',
                'price' => 85000,
                'original_price' => 110000,
                'stock' => 25,
                'sold_count' => 1200,
                'category' => 'Sports',
                'vendor' => 'FitLife Store',
                'images' => ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400'],
                'tags' => ['dumbbell', 'fitness', 'gym'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.6,
                'review_count' => 134,
                'variants' => [],
            ],
            [
                'title' => 'Luxury Gold Watch Premium Edition',
                'description' => 'Premium gold-plated wristwatch with genuine leather strap. Water-resistant to 50m. Sapphire crystal glass. Swiss movement.',
                'price' => 185000,
                'original_price' => 250000,
                'stock' => 18,
                'sold_count' => 3200,
                'category' => 'Fashion',
                'vendor' => 'Luxury Time NG',
                'images' => ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400'],
                'tags' => ['watch', 'luxury', 'fashion'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.8,
                'review_count' => 189,
                'variants' => [['label' => 'Color', 'options' => ['Gold', 'Silver', 'Rose Gold']]],
            ],
            [
                'title' => 'Designer Perfume Collection Set',
                'description' => 'Set of 3 premium designer perfumes. Long-lasting 12hr fragrance. Includes floral, musk, and citrus notes. Perfect gift set.',
                'price' => 45000,
                'original_price' => 65000,
                'stock' => 75,
                'sold_count' => 8900,
                'category' => 'Beauty',
                'vendor' => 'GlowUp Beauty',
                'images' => ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=400'],
                'tags' => ['perfume', 'fragrance', 'beauty'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.7,
                'review_count' => 456,
                'variants' => [['label' => 'Set', 'options' => ['Floral Trio', 'Musk Trio', 'Mixed']]],
            ],
            [
                'title' => '14K Gold Chain Necklace',
                'description' => 'Genuine 14K gold chain necklace. 22-inch length, lobster clasp. Hypoallergenic and tarnish-resistant. Premium jewelry.',
                'price' => 95000,
                'original_price' => 135000,
                'stock' => 12,
                'sold_count' => 5600,
                'category' => 'Fashion',
                'vendor' => 'Luxury Time NG',
                'images' => ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400'],
                'tags' => ['jewelry', 'gold', 'necklace'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.9,
                'review_count' => 234,
                'variants' => [['label' => 'Length', 'options' => ['18 inch', '20 inch', '22 inch', '24 inch']]],
            ],
            [
                'title' => 'Classic Beef Burger with Fries',
                'description' => 'Premium beef burger with cheddar, lettuce, tomato, and our special sauce. Served with crispy golden fries.',
                'price' => 3500,
                'original_price' => 5000,
                'stock' => 200,
                'sold_count' => 45200,
                'category' => 'Food',
                'vendor' => 'Naija Bites',
                'images' => ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400'],
                'tags' => ['burger', 'food', 'fast food'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.4,
                'review_count' => 1200,
                'variants' => [['label' => 'Size', 'options' => ['Regular', 'Double', 'Triple']]],
            ],
            [
                'title' => 'Premium Burger Meal Combo',
                'description' => 'Complete meal combo: burger, fries, drink, and dessert. Best value for your money! Perfect for lunch or dinner.',
                'price' => 6500,
                'original_price' => 8500,
                'stock' => 150,
                'sold_count' => 28400,
                'category' => 'Food',
                'vendor' => 'Naija Bites',
                'images' => ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400'],
                'tags' => ['burger', 'combo', 'meal'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.5,
                'review_count' => 890,
                'variants' => [],
            ],
            [
                'title' => 'Remote Control Racing Car',
                'description' => 'High-speed RC racing car with rechargeable battery. 30min runtime, 100m range. LED lights and sounds. Great for kids.',
                'price' => 8500,
                'original_price' => 12000,
                'stock' => 45,
                'sold_count' => 7800,
                'category' => 'Electronics',
                'vendor' => 'Kids Paradise',
                'images' => ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=400'],
                'tags' => ['toys', 'rc car', 'kids'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.3,
                'review_count' => 167,
                'variants' => [['label' => 'Color', 'options' => ['Red', 'Blue', 'Green', 'Yellow']]],
            ],
            [
                'title' => 'Educational Building Blocks Set 500pc',
                'description' => '500-piece building blocks set. Compatible with major brands. Includes carrying case and idea book. STEM learning toy.',
                'price' => 12000,
                'original_price' => 18000,
                'stock' => 60,
                'sold_count' => 15300,
                'category' => 'Electronics',
                'vendor' => 'Kids Paradise',
                'images' => ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=400'],
                'tags' => ['toys', 'blocks', 'educational'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.6,
                'review_count' => 312,
                'variants' => [['label' => 'Theme', 'options' => ['City', 'Space', 'Castle', 'Pirate']]],
            ],
            [
                'title' => 'Summer Beach Vacation Hat',
                'description' => 'Wide-brim straw beach hat. UV protection, foldable, lightweight. Perfect for your next vacation or beach day.',
                'price' => 4500,
                'original_price' => 7000,
                'stock' => 85,
                'sold_count' => 3400,
                'category' => 'Fashion',
                'vendor' => 'Adaeze Fashion Hub',
                'images' => ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400'],
                'tags' => ['hat', 'beach', 'summer', 'vacation'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.2,
                'review_count' => 98,
                'variants' => [['label' => 'Size', 'options' => ['S', 'M', 'L']]],
            ],
            [
                'title' => 'Travel Luggage Set 3-Piece',
                'description' => 'Premium 3-piece luggage set (20", 24", 28"). ABS hard shell, 360° spinner wheels, TSA lock. Lightweight and durable.',
                'price' => 85000,
                'original_price' => 120000,
                'stock' => 30,
                'sold_count' => 6700,
                'category' => 'Home',
                'vendor' => 'HomeGoods NG',
                'images' => ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400'],
                'tags' => ['luggage', 'travel', 'vacation'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.7,
                'review_count' => 445,
                'variants' => [['label' => 'Color', 'options' => ['Black', 'Navy', 'Silver', 'Rose Gold']]],
            ],
            [
                'title' => 'Adjustable Weight Bench Press',
                'description' => 'Heavy-duty adjustable weight bench. Supports up to 300kg. 7 back positions, 3 seat positions for versatile workouts.',
                'price' => 95000,
                'original_price' => 135000,
                'stock' => 10,
                'sold_count' => 2100,
                'category' => 'Sports',
                'vendor' => 'FitLife Store',
                'images' => ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400'],
                'tags' => ['gym', 'bench', 'fitness'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.8,
                'review_count' => 178,
                'variants' => [],
            ],
            [
                'title' => 'Resistance Bands Set 5-Pack',
                'description' => '5 resistance bands (10-50lbs). Latex-free, portable. Includes door anchor, handles, and carry bag. Perfect for home gym.',
                'price' => 8500,
                'original_price' => 12000,
                'stock' => 120,
                'sold_count' => 23400,
                'category' => 'Sports',
                'vendor' => 'FitLife Store',
                'images' => ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400'],
                'tags' => ['fitness', 'bands', 'exercise'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.5,
                'review_count' => 890,
                'variants' => [['label' => 'Level', 'options' => ['Light', 'Medium', 'Heavy', 'X-Heavy']]],
            ],
            [
                'title' => 'Smart LED Desk Lamp',
                'description' => 'LED desk lamp with wireless charging base. Adjustable color temp, brightness, and angle. USB-C port. Modern design.',
                'price' => 15000,
                'original_price' => 22000,
                'stock' => 40,
                'sold_count' => 8900,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=400'],
                'tags' => ['lamp', 'led', 'desk'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.6,
                'review_count' => 234,
                'variants' => [['label' => 'Color', 'options' => ['Black', 'White']]],
            ],
            [
                'title' => 'Leather Crossbody Bag',
                'description' => 'Genuine leather crossbody bag. Adjustable strap, multiple compartments, RFID blocking pocket. Perfect for everyday use.',
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 28,
                'sold_count' => 4500,
                'category' => 'Fashion',
                'vendor' => 'Adaeze Fashion Hub',
                'images' => ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400'],
                'tags' => ['bag', 'leather', 'fashion'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.4,
                'review_count' => 167,
                'variants' => [['label' => 'Color', 'options' => ['Brown', 'Black', 'Tan']]],
            ],
            [
                'title' => 'Queen Size Bed Sheet Set 6pc',
                'description' => '6-piece queen bedding set. 1800 thread count, microfiber, wrinkle-resistant. Includes sheets, pillowcases, and duvet cover.',
                'price' => 18000,
                'original_price' => 25000,
                'stock' => 90,
                'sold_count' => 18600,
                'category' => 'Home',
                'vendor' => 'HomeGoods NG',
                'images' => ['https://images.unsplash.com/photo-1631679706909-1844bbd0723f?w=400'],
                'tags' => ['bedding', 'home', 'sheets'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.3,
                'review_count' => 567,
                'variants' => [['label' => 'Color', 'options' => ['White', 'Grey', 'Navy', 'Blush']]],
            ],
            [
                'title' => 'Wireless Earbuds Pro ANC',
                'description' => 'Active noise cancelling earbuds. 8hr playback, IPX5 waterproof, wireless charging case. Crystal clear calls with AI noise reduction.',
                'price' => 22000,
                'original_price' => 35000,
                'stock' => 55,
                'sold_count' => 15200,
                'category' => 'Electronics',
                'vendor' => 'TechMall NG',
                'images' => ['https://images.unsplash.com/photo-1590658268037-6bf12f032f75?w=400'],
                'tags' => ['earbuds', 'audio', 'wireless'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.7,
                'review_count' => 678,
                'variants' => [['label' => 'Color', 'options' => ['Black', 'White', 'Navy']]],
            ],
            [
                'title' => 'Professional Chef Knife Set 5pc',
                'description' => 'German stainless steel chef knife set. Includes chef knife, santoku, bread knife, utility, and paring. Ergonomic handles.',
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 25,
                'sold_count' => 5600,
                'category' => 'Food',
                'vendor' => 'HomeGoods NG',
                'images' => ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400'],
                'tags' => ['kitchen', 'knife', 'cooking'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.6,
                'review_count' => 234,
                'variants' => [],
            ],
            [
                'title' => 'Men\'s Running Sneakers Ultra',
                'description' => 'Ultra-lightweight running shoes with responsive cushioning. Breathable mesh upper, rubber outsole. Perfect for daily runs.',
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 60,
                'sold_count' => 9200,
                'category' => 'Shoes',
                'vendor' => 'Kicks Hub NG',
                'images' => ['https://images.unsplash.com/photo-1590658268037-6bf12f032f75?w=400'],
                'tags' => ['sneakers', 'running', 'shoes'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => true,
                'rating' => 4.5,
                'review_count' => 345,
                'variants' => [['label' => 'Size', 'options' => ['39', '40', '41', '42', '43', '44', '45']]],
            ],
            [
                'title' => 'Vitamin C Brightening Serum',
                'description' => '20% Vitamin C serum with hyaluronic acid and Vitamin E. Brightens skin, reduces dark spots. 30ml bottle. Dermatologist tested.',
                'price' => 8500,
                'original_price' => 12000,
                'stock' => 100,
                'sold_count' => 18900,
                'category' => 'Beauty',
                'vendor' => 'GlowUp Beauty',
                'images' => ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=400'],
                'tags' => ['skincare', 'serum', 'vitamin c'],
                'is_dropshipping' => false,
                'ai_optimized' => false,
                'free_shipping' => false,
                'rating' => 4.5,
                'review_count' => 890,
                'variants' => [['label' => 'Size', 'options' => ['15ml', '30ml', '50ml']]],
            ],
        ];

        foreach ($products as $data) {
            $vendorId = $vendors[$data['vendor']] ?? null;
            if (!$vendorId) continue;

            Product::create([
                'id' => Str::uuid(),
                'vendor_id' => $vendorId,
                'title' => $data['title'],
                'description' => $data['description'],
                'price' => $data['price'],
                'original_price' => $data['original_price'],
                'stock' => $data['stock'],
                'sold_count' => $data['sold_count'],
                'category' => $data['category'],
                'images' => $data['images'],
                'tags' => $data['tags'],
                'is_dropshipping' => $data['is_dropshipping'],
                'ai_optimized' => $data['ai_optimized'],
                'free_shipping' => $data['free_shipping'],
                'rating' => $data['rating'],
                'review_count' => $data['review_count'],
                'variants' => $data['variants'],
                'is_active' => true,
                'seo_score' => rand(60, 95),
            ]);
        }
    }
}
